# Generated by Django 3.2.9 on 2021-12-01 12:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LearningApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choices',
            options={'ordering': ('-created',), 'verbose_name': 'Module Test Question Choice', 'verbose_name_plural': 'Module Test Question Choice'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('-created',), 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='modules',
            options={'ordering': ('-created',), 'verbose_name': 'Course Module', 'verbose_name_plural': 'Course Modules'},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ('-created',), 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ('-created',), 'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AddField(
            model_name='choices',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choices',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='module_name',
            field=models.CharField(max_length=200, verbose_name='Module Name'),
        ),
    ]
