# Generated by Django 3.2.9 on 2021-12-08 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearningApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modules',
            options={'ordering': ('-created',), 'verbose_name': 'Module', 'verbose_name_plural': 'Modules'},
        ),
    ]
