# Generated by Django 3.2.9 on 2021-12-10 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearningApp', '0003_alter_modules_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_questions', to='LearningApp.quiz'),
        ),
    ]
