# Generated by Django 3.2.9 on 2021-11-25 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usermanagement', '0005_auto_20211125_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_user', to='Usermanagement.institution'),
        ),
    ]
