# Generated by Django 3.2.9 on 2021-12-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usermanagement', '0002_auto_20211201_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Employee ID'),
        ),
    ]
