# Generated by Django 3.2.9 on 2021-12-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usermanagement', '0003_user_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='verified',
        ),
        migrations.AddField(
            model_name='institution',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ia Active'),
        ),
    ]
